services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - tasks_net
  backend:
    build: ../backend
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      POSTGRES_PORT: ${POSTGRES_PORT}
      IMAP_EMAIL: ${IMAP_EMAIL}
      EXTERNAL_PASS: ${EXTERNAL_PASS}

    ports:
      - "8000:8000"
    hostname: backend
    networks:
      - tasks_net
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ../frontend
    ports:
      - "80:80"  
    networks:
      - tasks_net
    depends_on:
      - backend

networks:
  tasks_net:
  
volumes:
  postgres-data:
